### ISSUE TITLE
Empty repo

### ISSUE THREAD

**Issue by RobLoach** [jstransformers/jstransformer-slm#1]
Is this happening? Seems weird to just have an empty repository. Delete it if it's not up?

**Comment by tunnckoCore** [comment]
I'll do them as soon as I can, I've just have more work this week. They are just published.

Just dont delete them, because will bug shitty travis and because I have `gitclone` cli that I use non-stop.

**Comment by RobLoach** [comment]
Then push this to GitHub, please. Otherwise, unpublish the npm package.

**Comment by ForbesLindesay** [comment]
You could even **start** each project by pushing to GitHub.  Then everyone can see your progress.
